# Generated by Django 2.1.7 on 2019-04-02 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(max_length=15, unique=True)),
                ('Password', models.TextField(max_length=32)),
                ('SQ1', models.TextField(max_length=100)),
                ('SA1', models.TextField(max_length=100)),
                ('SQ2', models.TextField(max_length=100)),
                ('SA2', models.TextField(max_length=100)),
                ('SQ3', models.TextField(max_length=100)),
                ('SA3', models.TextField(max_length=100)),
                ('TimeStamp', models.DateTimeField(auto_now=True)),
                ('LastLoginTimestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('PhotographerID', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False)),
                ('UserName', models.TextField(max_length=15, unique=True)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
                ('FirstName', models.TextField(max_length=50)),
                ('MiddleName', models.TextField(max_length=50)),
                ('LastName', models.TextField(max_length=50)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField(max_length=3)),
                ('Gender', models.TextField(max_length=1)),
                ('MobileNo', models.IntegerField(max_length=10)),
                ('Nationality', models.TextField(max_length=30)),
                ('AddressLine1', models.TextField(max_length=255)),
                ('AddressLine2', models.TextField(max_length=255)),
                ('AddressLine3', models.TextField(max_length=255)),
                ('Pincode', models.IntegerField(max_length=6)),
                ('Bio', models.TextField(max_length=500)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hitcounter', models.IntegerField(max_length=10)),
                ('Users', models.IntegerField(max_length=10)),
                ('Photos', models.IntegerField(max_length=10)),
                ('Comments', models.IntegerField(max_length=10)),
                ('Contests', models.IntegerField(max_length=10)),
                ('Likes', models.IntegerField(max_length=10)),
                ('Rating', models.IntegerField(max_length=10)),
                ('Participants', models.IntegerField(max_length=10)),
                ('Day', models.IntegerField(max_length=2)),
                ('Month', models.IntegerField(max_length=2)),
                ('Year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='PhotographerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Photographers'),
        ),
    ]
