# Generated by Django 2.2 on 2019-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographers',
            old_name='UserName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='UserName',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='password123', max_length=32),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
