# Generated by Django 2.2 on 2019-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographers',
            name='AddressLine2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='AddressLine3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='MiddleName',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='MobileNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='PhotographerID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='Pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Comments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Contests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Hitcounter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Participants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Photos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Users',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
