# Generated by Django 2.2 on 2019-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190404_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographers',
            name='PhotographerID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
