# Generated by Django 2.2 on 2019-04-05 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190404_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographers',
            name='Age',
        ),
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='login',
            name='SA1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='SA2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='SA3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='SQ1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='SQ2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='SQ3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='UserName',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='FirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='Gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='LastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='MobileNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='Nationality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='Pincode',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='photographers',
            name='UserName',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
