# Generated by Django 2.2 on 2019-04-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190406_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='PhotographerID',
        ),
    ]
