# Generated by Django 2.2 on 2019-04-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=100)),
                ('Count', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestRegisters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('ContestID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ContestName', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=500)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('UploadStartDate', models.DateField()),
                ('UploadEndDate', models.DateField()),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Categories')),
            ],
        ),
    ]
