# Generated by Django 2.2 on 2019-04-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='WinnerPictureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Pictures'),
        ),
        migrations.AddField(
            model_name='contestregisters',
            name='ContestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contests'),
        ),
        migrations.AddField(
            model_name='contestregisters',
            name='PictureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Pictures'),
        ),
    ]
