# Generated by Django 2.2 on 2019-04-06 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Comments', models.TextField(max_length=500)),
                ('TimeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('LikeID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Value', models.BooleanField(default=True)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('PictureID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=50, unique=True)),
                ('Description', models.TextField(max_length=500)),
                ('Location', models.TextField(max_length=30)),
                ('Keywords', models.TextField(max_length=255)),
                ('Views', models.IntegerField(default=0)),
                ('Visibility', models.BooleanField(default=True)),
                ('PhotoFile', models.FileField(upload_to='')),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('RatingID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Value', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
