# Generated by Django 2.1.7 on 2019-04-02 07:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('CommentID', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False)),
                ('Comments', models.TextField(max_length=500)),
                ('TimeStamp', models.DateTimeField(auto_now=True)),
                ('PhotographerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Photographers')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('LikeID', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False)),
                ('Value', models.BooleanField(default=True)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('PhotographerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Photographers')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('PictureID', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=50, unique=True)),
                ('Description', models.TextField(max_length=500)),
                ('Location', models.TextField(max_length=30)),
                ('Keywords', models.TextField(max_length=255)),
                ('Views', models.IntegerField(default=0, max_length=10)),
                ('Visibility', models.BooleanField(default=True)),
                ('PhotoFile', models.FileField(upload_to='')),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('PhotographerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Photographers')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('RatingID', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False)),
                ('Value', models.IntegerField(default=1, max_length=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('PhotographerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Photographers')),
                ('PictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Pictures')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='PictureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Pictures'),
        ),
        migrations.AddField(
            model_name='comments',
            name='PictureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Pictures'),
        ),
    ]
